parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     %%%%name%%%%
    database_user:     root
    database_password: root
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            %%%%locale%%%%

    # A secret key that's used to generate certain security-related tokens
    secret:            MnZasTgZaf68TTz7asd68
